# Generated by Django 6.0 on 2025-12-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawndigit',
            name='username',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
